### ISSUE TITLE
Can we add array pragmatically !???? 

### ISSUE THREAD

**Issue by anvesh523** [rajasharan/SearchableSpinner#1]
Right now in the demo program, the array is adding in xml file ( app:list="@array/all_languages ) ( static ) 
If I want to use dynamic values from my program, how can I add array in java file !?

**Comment by rajasharan** [comment]
@anvesh523 thanks for the suggestion

Either of these should now be possible

```
spinner.setList(getResources().getStringArray(R.array.all_languages));

String [] list = {"ONE", "TWO"};
spinner.setList(list);

```

**Comment by anvesh523** [comment]
Thank You ....
