### ISSUE TITLE
Using this library in fragment

### ISSUE THREAD

**Issue by anvesh523** [rajasharan/SearchableSpinner#2]
spinner1.setOnSelectionChangeListener(this); 
"this" is not able to use in fragment !
Please give me a solution....

**Comment by rajasharan** [comment]
"this" should be the instance of a class that implements SearchableSpinner.OnSelectionChangeListener

Your Fragment class can implement it then I would think it will work 

or you can simply use:
spinner1.getSelectedItem();

**Comment by anvesh523** [comment]
Thank you for replay...

mSpinner.setOnSelectionChangeListener(new SearchableSpinner.OnSelectionChangeListener() {
            @Override
            public void onSelectionChanged(String selection) {
                Toast.makeText(getActivity(), selection + " selected", Toast.LENGTH_SHORT).show();
            }
        });

I used like this.....
